### ISSUE TITLE
女子高铁占座不听劝阻掌掴乘警

### ISSUE THREAD

**Issue by ztw321** [majinqiawa/xxn#101]
10月1日，广东广州。网传一女子高铁占座不服劝阻，乘警多次警告无效后准备带离车厢，哪料女子直接出手给了乘警一耳光的视频引发热议，对此广州铁路公安处发布通报，2023年10月1日9时许，D1842次列车运行至佛山西站至广宁站区间，一女性旅客植某某占用他人座位被列车工作人员劝离后，仍在车厢过道吵闹，本次列车乘警到场处置过程中被其用手掌击打。该女子已被移交前方车站派出所处理，案件正在进一步办理中。

https://weibo.com/5044281310/NlXe9Am3c?refer_flag=1001030103_

https://www.bilibili.com/video/BV1L34y1V7GU/

警情通报：
https://weibo.com/3181348851/NlTefiJ7F
https://wx3.sinaimg.cn/mw690/bd9f87f3gy1hig676oz1mj20u011etfs.jpg

**Comment by majinqiawa** [comment]
抄收了，168小时内审核并根据审核结果处理(添加或未过审)
感谢您对仓库的贡献与支持！

**Comment by majinqiawa** [comment]
收录完成，感谢您对仓库的贡献与支持！
