### ISSUE TITLE
西安外国语大学63页ppt

### ISSUE THREAD

**Issue by bilibili-niang** [majinqiawa/xxn#102]
https://www.zhihu.com/topic/28639173/hot

**Comment by papothh76129** [comment]
https://github.com/papothh76129/DingYuJie

**Comment by majinqiawa** [comment]
抄收了，168小时内审核并根据审核结果处理(添加或未过审)
感谢您对仓库的贡献与支持！

**Comment by majinqiawa** [comment]
此事件经查证暂无权威媒体报道
仅凭PPT等不能完全证实情况
让子弹再飞一会，暂时不予收录。
感谢您对仓库的贡献与支持！
