### ISSUE TITLE
北极鲶鱼炫富事件

### ISSUE THREAD

**Issue by exumeOAO** [majinqiawa/xxn#103]
烦请添加北极鲶鱼炫富事件，十分感谢！
该事件时间很长，事发时间为2023年3月，最终处理时间为2023年10月。
参考链接：
以下为事发新闻：
https://www.thepaper.cn/newsDetail_forward_22430695
以下为最终处理新闻：
https://www.thepaper.cn/newsDetail_forward_24879782

**Comment by majinqiawa** [comment]
抄收了，此事件为敏感政治新闻，为保证仓库存活，暂时不予收录，还请理解。
感谢您对仓库的贡献与支持！
