### ISSUE TITLE
女子在新加坡诬告男友性侵自己

### ISSUE THREAD

**Issue by helianchichi** [majinqiawa/xxn#109]
时间：2023/10/02
事件：中国籍女子张露恬在新加坡诬告男友性侵并限制自己人身自由，新加坡高度重视大量警力调查，一个月后女子因害怕承认了虚假指控，新加坡以浪费公共资源和诬告判处女子5周监禁
来源：《新加坡联合早报》https://www.zaobao.com.sg/news/singapore/story20231002-1438927

**Comment by majinqiawa** [comment]
抄收了，168小时内审核并根据审核结果处理(添加或未过审)
感谢您对仓库的贡献与支持！

**Comment by majinqiawa** [comment]
收录完成，感谢您对仓库的贡献与支持！
