### ISSUE TITLE
女生因男生秋裤的裆部贴着自己被子，将裤子剪碎：认为这很猥琐

### ISSUE THREAD

**Issue by ztw321** [majinqiawa/xxn#110]
https://www.bilibili.com/video/BV18w411X7Pf/

https://weibo.com/6508016609/Np2ri3GOB

https://weibo.com/2028810631/NoTrZDhzX

10月20日，陕西西安。西安工业大学一女生在学校晾晒区晒被子，发现被子旁边晒着一条男生的秋裤。女生认为男生的秋裤裆部贴着她的被子，这让她感到不舒服，认为这很猥琐，然后在校园论坛发文称：等到八点让男生把秋裤取走，等不到人就把裤子剪了。后来她就用剪刀把秋裤剪烂了，并表示如果需要赔偿，可以联系她。10月21日，西安工业大学工作人员表示，自己需要先去了解一下，相关领导是否已经进行处

**Comment by majinqiawa** [comment]
抄收了，168小时内审核并根据审核结果处理(添加或未过审)
感谢您对仓库的贡献与支持！

**Comment by majinqiawa** [comment]
收录完成，感谢您对仓库的贡献与支持！
