### ISSUE TITLE
陈志显案

### ISSUE THREAD

**Issue by Ritashaiev** [majinqiawa/xxn#111]
【妻子：他太看重血缘了，禽兽不如！结婚十六年，结果3个孩子都不是亲生的-哔哩哔哩】 https://b23.tv/FmdHrjt
搜陈志显时未发现收录该案例

**Comment by majinqiawa** [comment]
抄收了，168小时内审核并根据审核结果处理(添加或未过审)
感谢您对仓库的贡献与支持！

**Comment by majinqiawa** [comment]
收录完成，感谢您对仓库的贡献与支持！
