### ISSUE TITLE
女学生上公交车后没有座位，大骂其他乘客脑残

### ISSUE THREAD

**Issue by ztw321** [majinqiawa/xxn#122]
https://m.163.com/v/video/VOK1N03L6.html?spss=adap_pc
https://baijiahao.baidu.com/s?id=1784274946960380322&wfr=spider&for=pc
【女孩坐公交车没人让座，瞬间崩溃怒骂大爷大妈！【1323期】-哔哩哔哩】 https://b23.tv/7ZMzE24

后续:https://m.weibo.cn/detail/4974970759548677

**Comment by majinqiawa** [comment]
抄收了，168小时内审核并根据审核结果处理(添加或未过审)
感谢您对仓库的贡献与支持！

**Comment by majinqiawa** [comment]
收录完成，感谢您对仓库的贡献与支持！
