### ISSUE TITLE
女辅警因追星扬言要开盒网友并查开房记录

### ISSUE THREAD

**Issue by qingmolt** [majinqiawa/xxn#123]
https://m.nbd.com.cn/articles/2023-12-09/3156092.html

https://mil.sina.cn/2023-12-09/detail-imzxmfyt6154559.d.html?from=wap

**Comment by majinqiawa** [comment]
抄收了，168小时内审核并根据审核结果处理(添加或未过审)
感谢您对仓库的贡献与支持！

**Comment by majinqiawa** [comment]
收录完成，感谢您对仓库的贡献与支持！
