### ISSUE TITLE
女子在服装店“零元购”，被抓现行后大喊“我没拿”，店员怒报警

### ISSUE THREAD

**Issue by ztw321** [majinqiawa/xxn#126]
1月6日四川成都，一名男子分享了服装店内的一段监控视频，称在店内发现了一名小偷来偷衣服。一名穿红色外套戴口罩、提着一个大袋子的女子走进店内，店员正在给其他顾客介绍衣服。女子在货架上选好衣服，趁四下无人时取下一件，放进大袋子里。此时店员回头时正好看到，走到女子身边将其手中的袋子打开，拿出了衣服。店员抓住女子怒斥，报警后带到店外，民警到达现场后，附近商户称自家也有物品被偷，民警将偷衣服的女子带走调查。

https://www.bilibili.com/video/BV1Ew411u7DV/

**Comment by majinqiawa** [comment]
抄收了，168小时内审核并根据审核结果处理(添加或未过审)
感谢您对仓库的贡献与支持！

**Comment by majinqiawa** [comment]
收录完成，感谢您对仓库的贡献与支持！
