### ISSUE TITLE
女子仅退款后取走上千件快递！商家：平台申诉不成功，已报警

### ISSUE THREAD

**Issue by ztw321** [majinqiawa/xxn#128]
https://www.bilibili.com/video/BV1Tg4y1Q7b7/

https://www.bilibili.com/video/BV1jc411t7bd/

**Comment by majinqiawa** [comment]
抄收了，168小时内审核并根据审核结果处理(添加或未过审)
感谢您对仓库的贡献与支持！

**Comment by majinqiawa** [comment]
收录完成，感谢您对仓库的贡献与支持！
