### ISSUE TITLE
最近的地铁zw事件补充

### ISSUE THREAD

**Issue by 2652237653** [majinqiawa/xxn#13]
最近的地铁事件补充zw向纪检委的说明书，我觉得每一段文字都十分逆天
![说明书](https://github.com/majinqiawa/xxn/assets/94550140/35420c77-7ea2-4217-b3d4-76d338279aa5)

**Comment by 2652237653** [comment]
每一段都是经典

**Comment by fantaojie** [comment]
真是无语 简直给党招黑 你做错事 你道歉  觉得全世界欠你一样

**Comment by PatrickkZhao** [comment]
我以为这文字是其他人转述出来的，真的是她本人原话吗？

**Comment by lizilong1993** [comment]
报警威胁我  这里真的绷不住了。。。。
