### ISSUE TITLE
女孩燃放烟花时疑故意点燃店家装饰物，店主：已报警处理

### ISSUE THREAD

**Issue by ztw321** [majinqiawa/xxn#135]
【女孩燃放烟花时疑故意点燃店家装饰物，店主：已报警处理】 https://www.bilibili.com/video/BV1kK421y7WD

**Comment by majinqiawa** [comment]
抄收了，168小时内审核并根据审核结果处理(添加或未过审)
感谢您对仓库的贡献与支持！

**Comment by majinqiawa** [comment]
当事人仅4岁，想搞破坏这种是小朋友人之常情，小时候也不知道，家教不到位我认为才是主要原因，暂时不予收录

**Comment by majinqiawa** [comment]
这件事我个人认为，小时候想捣乱这是正常的，但是需要家长去加以管教去正确引导，责任大部分不在小朋友，在于家长管教不力我认为是主要的，我发了B站置顶动态大家投票探讨一下

**Comment by majinqiawa** [comment]
家教问题的话就超出仓库范围了，我认为四岁小朋友是没有这种自我约束力的，辨别是非的能力也没有那么成熟
