### ISSUE TITLE
因感情纠葛起争执，女生网上发帖造谣男同学是强奸犯，致其被停学

### ISSUE THREAD

**Issue by ztw321** [majinqiawa/xxn#139]
https://weibo.com/7516679696/O2ZP5pCcc

【因感情纠葛起争执，女生网上发帖造谣男同学是强奸犯，致其被停学】 https://www.bilibili.com/video/BV1fH4y177PN

近日，河南信阳。商城县人民法院审理一起通过网络散播不实消息，侵犯他人名誉权的案件。邓某某与夏某某在商城县某中学就读时相识，大学期间，邓某某与夏某某因感情纠葛发生争执，夏某某向公安局控告被邓某某强奸，后经公安局审查认为没有犯罪事实，并决定不予立案。2023年9月，夏某某安排其朋友使用虚拟的微博账户，多次在邓某某现就读的江西某职业学院“超话”中发布帖子，散播邓某某为强奸犯的不实信息，并引起众多网友围观评论，后邓某某所在学校以上述事宜严重影响学校声誉为由，对邓某某进行停学处理。

**Comment by majinqiawa** [comment]
抄收了，168小时内审核并根据审核结果处理(添加或未过审)
感谢您对仓库的贡献与支持！

**Comment by majinqiawa** [comment]
收录完成，感谢您对仓库的贡献与支持！
