### ISSUE TITLE
长沙宝马女司机闯红灯冲撞学生，被抓后撒泼不肯下车：我被脑控了

### ISSUE THREAD

**Issue by ztw321** [majinqiawa/xxn#142]
https://k.sina.com.cn/article_6212976462_172527f4e02001bn0o.html

https://m.163.com/dy/article/ISRNC7HV0556170N.html

https://weibo.com/1912299425/O4aNs9J2s?refer_flag=1001030103_

**Comment by ztw321** [comment]
警情通报
https://mp.weixin.qq.com/s/8rdM5uHMmfCmBSpyYHsdbw

**Comment by majinqiawa** [comment]
抄收了，168小时内审核并根据审核结果处理(添加或未过审)
感谢您对仓库的贡献与支持！

**Comment by majinqiawa** [comment]
收录完成，感谢您对仓库的贡献与支持！
