### ISSUE TITLE
女子自称被丈夫泼酒点燃后烧伤，警方：不予立案！

### ISSUE THREAD

**Issue by ztw321** [majinqiawa/xxn#144]
【女子被丈夫泼白酒点燃烧伤，妇联：可能是她自己烧的，警方还在取证】 https://www.bilibili.com/video/BV1Vu4m1K7Ph/

https://baijiahao.baidu.com/s?id=1794453500845491464&wfr=spider&for=pc

https://baijiahao.baidu.com/s?id=1794503293307677588&wfr=spider&for=pc

https://weibo.com/2382356540/O6w9OD4BS?refer_flag=1001030103_

警情通报：https://mp.weixin.qq.com/s/ewmgn5yKS0ZWcKSRjd48gA

**Comment by majinqiawa** [comment]
抄收了，168小时内审核并根据审核结果处理(添加或未过审)
感谢您对仓库的贡献与支持！

**Comment by majinqiawa** [comment]
收录完成，感谢您对仓库的贡献与支持！
