### ISSUE TITLE
男子吐槽遭尾随骚扰：被女子抱住称“你好帅”，还追上公交车

### ISSUE THREAD

**Issue by ztw321** [majinqiawa/xxn#148]
【男子吐槽遭尾随骚扰：被女子抱住称“你好帅”，还追上公交车】 https://www.bilibili.com/video/BV1nr421b7B9/

https://weibo.com/6532102014/O7wT2cSgl?refer_flag=1001030103_

https://weibo.com/5145725878/O7xuXa5wc?refer_flag=1001030103_

**Comment by majinqiawa** [comment]
收录完成，感谢您对仓库的贡献与支持！
