### ISSUE TITLE
女子醉酒后乘坐出租车 到地方不愿下车疯狂踢踹司机

### ISSUE THREAD

**Issue by ztw321** [majinqiawa/xxn#149]
https://www.douyin.com/video/7351770491129990400
https://kan.china.com/article/2781091.html

【女子坐出租车，突然狂踹司机：这是我的车！司机一脸懵逼【1437期】】 https://www.bilibili.com/video/BV1wA4m1A7Fq
视频开头

**Comment by majinqiawa** [comment]
抄收了，168小时内审核并根据审核结果处理(添加或未过审)
感谢您对仓库的贡献与支持！

**Comment by majinqiawa** [comment]
收录完成，感谢您对仓库的贡献与支持！
