### ISSUE TITLE
保时捷女司机撞车后砸门吓哭小孩

### ISSUE THREAD

**Issue by ztw321** [majinqiawa/xxn#150]
【保时捷女司机与车辆擦挂 狂踹对方车门叫嚣“撞死你也就20万的事”】 https://www.bilibili.com/video/BV1pJ4m1p7ag/

https://weibo.com/5665811463/O9weXxAzQ?refer_flag=1001030103_

https://weibo.com/1496814565/O9yElqHb4?refer_flag=1001030103_

警情通报：https://mp.weixin.qq.com/s/1234-mcvB7PpNKocOY2T8g

**Comment by majinqiawa** [comment]
抄收了，168小时内审核并根据审核结果处理(添加或未过审)
感谢您对仓库的贡献与支持！

**Comment by majinqiawa** [comment]
收录完成，感谢您对仓库的贡献与支持！
