### ISSUE TITLE
女中学生对男生狂扇耳光薅头发

### ISSUE THREAD

**Issue by ztw321** [majinqiawa/xxn#155]
https://baijiahao.baidu.com/s?id=1797023624336070234

【官方通报女中学生狂扇男生耳光薅头发：情况属实，已进行心理疏导】 https://www.bilibili.com/video/BV1GH4y1P7Ze/

**Comment by majinqiawa** [comment]
抄收了，168小时内审核并根据审核结果处理(添加或未过审)
感谢您对仓库的贡献与支持！

**Comment by majinqiawa** [comment]
收录完成，感谢您对仓库的贡献与支持！
