### ISSUE TITLE
女子骑车摔倒女孩上前帮忙被“反咬一口”，好心姐姐拿监控证清白

### ISSUE THREAD

**Issue by ztw321** [majinqiawa/xxn#156]
https://weibo.com/2620088113/ObmXVFO9e?refer_flag=1001030103
https://weibo.com/1744332207/Obm83yQ6R

https://k.sina.com.cn/article_2026873597_m78cfa2fd03301bn1k.html

https://www.dzwww.com/xinwen/shehuixinwen/202404/t20240425_14062595.htm

【女子骑车摔倒女孩上前帮忙被“反咬一口”，好心姐姐拿监控证清白】 https://www.bilibili.com/video/BV1LF4m1w7PR/

**Comment by majinqiawa** [comment]
此事件系讹传，因此不予收录，感谢您对仓库的贡献与支持！
另附相关依据：
【#警方辟谣高中生好心扶老人被诬是肇事者#，当时两车发生碰撞】近日，一段名为“高中生好心扶老人却被诬陷是肇事者，附近商户调出监控证清白”的视频在网上流传，引发关注。红星新闻记者从宜宾交警部门获悉，事发时两人驾驶的车辆发生碰撞，辖区交警对此进行了调查处理。女生冷静下来后，将老人送到附近医院检查，老人除两手臂受轻微皮外伤外并无大碍。事后，老人并未纠缠此事，双方各自骑车离开，并未出现“老人诬陷女生、拉住女生不让走”的情形。女生使用的共享电单车有商业保险，因此事后交警对双方进行询问，形成笔录并同步录音录像。
