### ISSUE TITLE
2020-11-20 清华学姐诬陷学弟“性骚扰”事件

### ISSUE THREAD

**Issue by QG99k** [majinqiawa/xxn#16]
https://www.thepaper.cn/newsDetail_forward_10071513
https://www.bilibili.com/video/BV1Xa411c787/?spm_id_from=333.337.search-card.all.click&vd_source=dcb6b8f58c28dccd8058241be2781a28
![Uploading .png…]()

**Comment by Lulllabye** [comment]
这不腚姐啊，里程碑式的人物

**Comment by majinqiawa** [comment]
抄收了，这个事件当时也有了解，24小时内登记，谢谢喵
