### ISSUE TITLE
2019【女员工因担心走光上班打伞遭开除法院裁定公司解约合法】

### ISSUE THREAD

**Issue by Rakau** [majinqiawa/xxn#170]
https://finance.sina.com.cn/jjxw/2024-06-11/doc-inaykqrw3742422.shtml

**Comment by majinqiawa** [comment]
抄收了，审核后根据审核结果处理（添加或未过审）
回忆对仓库的贡献与支持！

**Comment by majinqiawa** [comment]
收录完成，感谢您对仓库的贡献与支持！
