### ISSUE TITLE
徒步旅行女主播路边直播时被车撞

### ISSUE THREAD

**Issue by ztw321** [majinqiawa/xxn#172]
https://weibo.com/1618051664/OlXop9UJo?refer_flag=1001030103

【徒步旅行女主播公路边直播时被车撞，医院：暂无生命危险】 https://www.bilibili.com/video/BV1kE421A7j5/

**Comment by majinqiawa** [comment]
抄收了，审核后根据审核结果处理（添加或未过审）
感谢您对仓库的贡献与支持！

**Comment by majinqiawa** [comment]
我认为此次事件中黑车没有保持安全距离负事故主要责任，故不属于仓库收录范围，感谢您对仓库的支持与理解！
