### ISSUE TITLE
女子趴小区地上晒背，被女司机开车碾压

### ISSUE THREAD

**Issue by ztw321** [majinqiawa/xxn#187]
近日，江苏苏州。据荔枝新闻报道，一名女子杨某趴在小区的道路上“晒背”，结果被一辆经过的汽车给撞了。民警赶到现场时，受伤女子已被送往医院。行车记录仪显示，当时，一名女子在路上铺着瑜伽垫，全副“武装”，撑着遮阳伞悠闲地在道路上“趴着晒背”，四周也没有任何警示遮挡。汽车驾驶员闵女士回想起事发时的一幕，依然是惊魂未定，自己启动汽车倒出车位后，压根就没看到地上还躺着个人，直到车外有人在呼救，才意识到压到人。

【女子趴小区地上晒背，路过车主毫不知情开车碾压，交警：司机主责】 https://www.bilibili.com/video/BV1ei421a7eM/

https://baijiahao.baidu.com/s?id=1807661381424123128

https://www.sohu.com/a/801546309_349247

https://www.163.com/dy/article/J9PPVIIK0514R9KQ.html

**Comment by majinqiawa** [comment]
抄收了，审核后根据审核结果处理（添加或未过审）
感谢您对仓库的贡献与支持！

**Comment by majinqiawa** [comment]
收录完成，感谢您对仓库的贡献与支持！
