### ISSUE TITLE
路虎女逆行对方不让，恼羞成怒狂扇小伙十几巴掌！

### ISSUE THREAD

**Issue by ztw321** [majinqiawa/xxn#188]
https://www.bilibili.com/video/BV1qH4y1F7Da/

【青岛路虎女司机逆行插队打人还逃逸的后续，据媒体报道，女方不是公务员，但家里是有钱人，目前女方不愿意赔钱，她的家属，理都不理这个男子。】 https://www.bilibili.com/video/BV1qyHgeuEbb/

https://weibo.com/7516679696/OuHfQznSo?refer_flag=1001030103

https://weibo.com/ttarticle/p/show?id=2309405073039803940901

**Comment by majinqiawa** [comment]
抄收了，审核后根据审核结果处理（添加或未过审）
感谢您对仓库的贡献与支持！

**Comment by majinqiawa** [comment]
收录完成，感谢您对仓库的贡献与支持！
