### ISSUE TITLE
建议缓存网页

### ISSUE THREAD

**Issue by SnowleopardXI** [majinqiawa/xxn#19]
建议添加日期，并对部分链接网页、视频保存
如图，保存为webarchive和mp4
![Screenshot 2023-06-15 at 16 17 13](https://github.com/majinqiawa/xxn/assets/69493681/1aa2ee37-642b-48d5-935b-f63d74f7382e)
![Screenshot at Jun 15 16-18-43](https://github.com/majinqiawa/xxn/assets/69493681/f17ceeb3-9292-48b2-ad72-e5b05ad883e7)

**Comment by majinqiawa** [comment]
另外根据评论区大家的意见，新闻快照什么的我会搞的
我打算存两个新闻的截图，同时存一个B站客观报道的360p视频，后续一起传在文件夹

——摘自我自己的评论

72小时内把这些快照备份之类的搞定
