### ISSUE TITLE
河北邯郸两女子为了拍照好看，私自将咖啡店的海报撕下来！

### ISSUE THREAD

**Issue by ztw321** [majinqiawa/xxn#193]
https://weibo.com/6418480627/Ovrr9DqFv?refer_flag=1001030103

【逆天！俩小仙女为拍照擅自撕掉店家海报！这啥素质？】 https://www.bilibili.com/video/BV12QpMeSEvv

【女子欲在咖啡店门口拍照，嫌店家门上海报太丑，擅自撕下来扔掉】 https://www.bilibili.com/video/BV1NapTeyEwT

https://k.sina.com.cn/article_1644948230_m620beb060330148ni.html

https://www.163.com/dy/article/JBBM4PK605566S4B.html

**Comment by majinqiawa** [comment]
抄收了，审核后根据审核结果处理（添加或未过审）
感谢您对仓库的贡献与支持！

**Comment by majinqiawa** [comment]
收录完成，感谢您对仓库的贡献与支持！
