### ISSUE TITLE
女子退穿过衣服遭拒怒点火烧掉

### ISSUE THREAD

**Issue by ztw321** [majinqiawa/xxn#195]
导语：9月6日，安徽合肥。一女子要求换衣服，被店主拒绝，因为店主发现衣服被穿过，领口发黄，有汗味，吊牌也摘了，影响再次销售。之后女子在店内吵闹拍桌子，店主报警后，警察将女子劝走，没想到警察走后，女子又返回店里点燃了衣服。

https://weibo.com/1789681642/OvRlpm90e

【有什么大不了的嘞？ 女子退穿过衣服遭拒后，竟在店内点火烧掉】 https://www.bilibili.com/video/BV12yp4eTEMn/

https://www.jnnews.tv/p/1074170.html

**Comment by majinqiawa** [comment]
抄收了，审核后根据审核结果处理（添加或未过审）
感谢您对仓库的贡献与支持！

**Comment by majinqiawa** [comment]
收录完成，感谢您对仓库的贡献与支持！
