### ISSUE TITLE
女子攀爬到佛像上，不停念叨“我是活菩萨”“都给我跪下”

### ISSUE THREAD

**Issue by ztw321** [majinqiawa/xxn#196]
【女子寺庙内站佛像上大喊“哪来的我”，景区：报警后已被警方带走】 https://www.bilibili.com/video/BV1MTtTe8EB5/

【网友爆料女子攀爬到佛像上，不停念叨“我是活菩萨”“都给我跪下”】 https://www.bilibili.com/video/BV1T4tKeoEdj/

https://weibo.com/5145725878/OwXy9pTYN

https://www.sohu.com/a/809023942_121350168

https://www.163.com/v/video/VNB4Q76SI.html

**Comment by majinqiawa** [comment]
收录完成，感谢您对仓库的贡献与支持！
