### ISSUE TITLE
【补充】女子攀爬到佛像上，不停念叨“我是活菩萨”“都给我跪下” 官方通报

### ISSUE THREAD

**Issue by ztw321** [majinqiawa/xxn#198]
https://weibo.com/1887344341/OxpxpF5cR

原文出自应县融媒微信视频号
![1](https://github.com/user-attachments/assets/59b8ad79-bc71-48f0-8b85-c66fa5e01cbf)

**Comment by majinqiawa** [comment]
抄收了，审核后根据审核结果处理（添加或未过审）
感谢您对仓库的贡献与支持！

**Comment by majinqiawa** [comment]
收录完成，感谢您对仓库的贡献与支持！
