### ISSUE TITLE
重庆脚踩外卖员脸部女子被警方带走

### ISSUE THREAD

**Issue by ztw321** [majinqiawa/xxn#199]
https://weibo.com/6124642021/OACvtmqAD

【10.8重庆妹子暴打外卖小哥事件完整版，殴打爆踩脑袋，后续被刑拘！】 https://www.bilibili.com/video/BV1DV2HYiEg8

警情通报：https://weibo.com/7362003610/OACgm7N7G
https://wx1.sinaimg.cn/mw690/0082edrIly1huf5vght5hj30m813iwfz.jpg

**Comment by majinqiawa** [comment]
抄收了，审核后根据审核结果处理（添加或未过审）
感谢您对仓库的贡献与支持！

**Comment by majinqiawa** [comment]
收录完成，感谢您对仓库的贡献与支持！
