### ISSUE TITLE
母女两人高铁霸座 乘警多次劝说无效被持刀威胁

### ISSUE THREAD

**Issue by ztw321** [majinqiawa/xxn#211]
https://www.bilibili.com/video/BV1bCqHYCEK8/

https://www.bilibili.com/video/BV1DkqHY5Eap/

https://weibo.com/2011075080/P41o4ABtp

https://baijiahao.baidu.com/s?id=1817865060927292308

https://finance.sina.cn/2024-12-09/detail-incywcvt2588196.d.html

**Comment by majinqiawa** [comment]
抄收了，审核后根据审核结果处理（添加或未过审）
感谢您对仓库的贡献与支持！

**Comment by majinqiawa** [comment]
收录完成，感谢您对仓库的贡献与支持！
