### ISSUE TITLE
9.18 女子打车30公里不给钱反打司机

### ISSUE THREAD

**Issue by ztw321** [majinqiawa/xxn#212]
https://www.bilibili.com/video/BV1yYz2Y5E3H/

https://weibo.com/6016020391/OxP2O2luV

https://www.ixigua.com/7416714972380840484

**Comment by majinqiawa** [comment]
抄收了，审核后根据审核结果处理（添加或未过审）
感谢您对仓库的贡献与支持！

**Comment by majinqiawa** [comment]
收录完成，感谢您对仓库的贡献与支持！
