### ISSUE TITLE
女子放火烧山只为捡塑料瓶 以为“扑火后会留下塑料瓶子”

### ISSUE THREAD

**Issue by ztw321** [majinqiawa/xxn#213]
https://www.bilibili.com/video/BV1iUquYQEn8/

https://baijiahao.baidu.com/s?id=1818023147949843206

https://weibo.com/1644489953/P4fhaDgdY

https://weibo.com/2342024544/P4eSpxkff

**Comment by majinqiawa** [comment]
抄收了，审核后根据审核结果处理（添加或未过审）
感谢您对仓库的贡献与支持！

**Comment by majinqiawa** [comment]
收录完成，感谢您对仓库的贡献与支持！
