### ISSUE TITLE
添加新案件整理到吐血啊QAQ

### ISSUE THREAD

**Issue by majinqiawa** [majinqiawa/xxn#23]

**Comment by majinqiawa** [comment]
感谢一位巨佬帮我按时间做了分类，我先继续登记新闻，有空再把剩下这些分类，整理这些实在是太费时间了

另外快照加上了，是web archive的WARC快照

**Comment by majinqiawa** [comment]
先歇一会在继续整理了，还有6个没登记

**Comment by zkung** [comment]
为啥不用chatgpt做分类 直接提取结构化数据啊

**Comment by majinqiawa** [comment]
你说得对，但是你们提的issues有的只有标题，有的只有链接，还有的只是告诉我是什么事，而且最终材料也是需要我自己去收集的，chatgpt不可能做到收纳归整这些2023年到2021年的新闻，他的时效性不行，还是得我自己来，chatgpt也不能生成浏览器快照，也不能把新闻截图帮我找好
