### ISSUE TITLE
广东xxn酒瓶爆头事件

### ISSUE THREAD

**Issue by TosakaMeow** [majinqiawa/xxn#27]
2021年12月14日，广东东莞。有网友称，因排队纠纷，一女生用玻璃瓶打伤一男生头部。广东医科大学相关人士告诉澎湃新闻，家长已带女生回家，校方将根据警方调查结果处理。至今貌似无结果。

**Comment by majinqiawa** [comment]
抄收了，24小时内核实并登记，谢谢
