### ISSUE TITLE
上海徐汇中学一女生进男生浴室偷拍，18名男生维权遭老师痛批

### ISSUE THREAD

**Issue by Eason0731** [majinqiawa/xxn#28]
时间：2023年3月27日
人物：女学生（名字搜不到了），女老师胡晓思
相关链接：https://zhuanlan.zhihu.com/p/617417255

**Comment by majinqiawa** [comment]
这个大部分同志都知道了，由于此事件社会舆论过大，有可能造成仓库沦陷，暂时不予收录，谢谢
