### ISSUE TITLE
华东理工大学的区别对待，以及四川大学和天津大学的xxn

### ISSUE THREAD

**Issue by JiangLaime** [majinqiawa/xxn#29]
2011年，华东理工大学一男生因盗窃被开除。
2016年，华东理工大学一男生因盗窃平板被开除。
以上事件没搜到对应新闻链接
2021年，华东理工大学一女生盗窃，据说被保研，后续结果未知，但肯定没被开除。

四川大学
2021 年 12 月 5 日晚，四川大学文学与新闻学院一男生在江安校区文科楼 6 楼女卫生间偷拍，被开除。链接如下：
https://www.thepaper.cn/newsDetail_forward_15731463
https://zhuanlan.zhihu.com/p/442350060
2023年张薇事件，不用多说了，据说只是个留校察看。

2021年一女子被男子泼奶茶，男子被拘留
https://www.thepaper.cn/newsDetail_forward_12675096
天津大学
2023年，韩卓燕，18级数学与应用，在食堂当众往男生头上扣饭，赔偿300了事。
https://www.bilibili.com/video/BV1zu4y1o7ok/?spm_id_from=333.337.search-card.all.click&vd_source=1fb8c405be36015edab51ee5efb1b0a2

**Comment by majinqiawa** [comment]
华东理工此事已收录，请注意查看没有此事件再提issues
四川大学张薇貌似收录了稍后再次核对
2021年四川大学泼奶茶事件需核实是否为女性问题才导致泼奶茶，男性新闻我后面有空再做个仓库，并且也不少收集男性新闻的了
天津大学这个已经收录了，你提issues的时候一点不看仓库内容的吗？

**Comment by JiangLaime** [comment]
你好，仓库内容我看了的，我本意是提供一些学校区别对待的情节。issue是分为三段的。
第一段是华理的区别对待。
第三段的泼奶茶好像不是川大的，是成都街头的一件事。但是天大面对同样的扣饭的处理我觉得处理不妥当。（这段可能不合适，也可能是因为当事人已和解）

细想了一下可能提供的内容可能不是很符合主题，请忽略。



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月16日 20:03 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [majinqiawa/xxn] 华东理工大学的区别对待，以及四川大学和天津大学的xxn (Issue #29) |

Closed #29 as completed.
