### ISSUE TITLE
网约车司机拒绝逆行，反遭女乘客报警

### ISSUE THREAD

**Issue by AOQNRMGYXLMV** [majinqiawa/xxn#32]
## 时间
2021年8月18日

## 地点
深圳

## 事件

一网约车司机在接单后经过一个右转路口时，被乘客要求逆行横穿马路。司机称这种行为属于逆行，不能这么走，随后司机与乘客在车中争吵起来。

乘客认为司机想绕路“宰客”
“我家住在这里，我怎么不知道呢”
“我们周围所有小区都是往这边转的”

司机师傅坚持拒绝逆行违法
“这只能是右转的”
“它那个是属于逆行的知道吗”

最后，乘客情绪十分激动，称要向交警投诉该司机绕行

## 链接

- [乘客要求司机逆行，称全小区都这样开？交警核查！网友：干得漂亮 ](https://www.sohu.com/a/485663719_121117490)
- [网约车司机拒绝逆行，反遭乘客报警？后续来了！](https://news.sina.cn/2021-08-24/detail-ikqciyzm3336151.d.html?wm=3049_0032)

**Comment by majinqiawa** [comment]
抄收了，由于目前issues过多，168小时内对新闻进行审核并登记
