### ISSUE TITLE
女子高速欲跳车自杀，的哥被迫停车劝导致追尾崩溃痛哭，女乘客自杀身亡

### ISSUE THREAD

**Issue by AOQNRMGYXLMV** [majinqiawa/xxn#33]
## 时间
2022年12月31日

## 地点
四川内江

## 事件
司机载一女乘客在高速路上行驶时，女乘客情绪激动试图开门欲跳车，司机被逼停。在出租车司机好心劝导提醒上车时，后方发生追尾事故，的哥瞬间崩溃失声痛哭。

事故造成两次追尾，多辆车辆受损，最终司机被判负15%的责任，而涉事的女乘客因为跑到马路对面被撞身亡。

## 链接

- [女子高速欲跳车自杀，的哥被迫停车劝导致追尾崩溃痛哭，女乘客自杀身亡司机疑承担15%责任，如何看待此事？](https://www.zhihu.com/question/576335402)
- [良言难劝该死鬼 慈悲不度自绝人 什么样的爱会让人一心求死？ 求死还要害了别人？ 司机真是到了八辈霉 拉了这样的人](https://www.bilibili.com/video/BV1vR4y1U7oe)

**Comment by majinqiawa** [comment]
抄收了，由于目前issues过多，168小时内对新闻进行审核并登记
