### ISSUE TITLE
女子为赖账诬陷司机袭胸

### ISSUE THREAD

**Issue by AOQNRMGYXLMV** [majinqiawa/xxn#34]
## 事件
2021年9月

## 地点
深圳

## 事件
深圳一女子打车想赖掉车费，诬陷司机摸了她的胸，还叫嚣让男友打人。

司机无奈报警处理，还好车内监控证明司机清白。

在监控的铁证之下，这名女子终于承认自己是因为某些事想赖掉车费，后来在民警同志的调解之下，女子向司机师傅赔礼道歉，并赔偿4000块钱。

## 链接

- [深圳一女子打车想赖掉车费，诬陷司机摸了她的胸，还叫嚣让男友打人](https://www.bilibili.com/video/BV1JD4y197bJ)
- [深圳女子想赖车费，诬陷的哥摸她胸，当民警面辱骂逼迫男友打的哥](https://www.sohu.com/a/427579261_100023190)

**Comment by majinqiawa** [comment]
抄收了，由于目前issues过多，168小时内对新闻进行审核并登记
