### ISSUE TITLE
女乘客强吻出租车司机 事后给15元“精神损失费” 

### ISSUE THREAD

**Issue by AOQNRMGYXLMV** [majinqiawa/xxn#35]
## 时间

2020年12月31日

## 地点

四川江油

## 事件

江油一位出租车司机送顾客过程中，遭到了女乘客的强吻。

从该司机向记者提供的行车记录仪中可以看到，在女乘客到达目的地之后，趁着给钱之际，毫无征兆地一把搂过出租车司机的头，上去就开始强吻出租车司机。

出租车司机毫无防备，被这位女乘客的举动给吓坏了，赶紧侧脸躲避，虽然司机极力反抗，但依旧没能逃脱“二次强攻”。

事后这名女子多给了司机15块钱，算是精神损失与安慰费。

## 链接

- [女乘客强吻出租车司机 事后给15元“精神损失费” ](https://www.sohu.com/a/442464746_156578)
- [对话被女乘客强吻的出租车司机：15元精神损失费不对等](https://finance.sina.com.cn/tech/2021-01-03/doc-iiznezxt0297564.shtml)

**Comment by majinqiawa** [comment]
抄收了，由于目前issues过多，168小时内对新闻进行审核并登记
