### ISSUE TITLE
嘉兴一女子凌晨打黑车被司机尾随至家门口，事后女子道歉称司机只是想要回车费

### ISSUE THREAD

**Issue by AOQNRMGYXLMV** [majinqiawa/xxn#36]
## 时间

2022年6月13日

## 地点

浙江嘉善

## 事件

浙江嘉兴一女子发布一段“深夜回家遭黑车司机跟随敲门”的监控视频，视频下方，该网友表示“网约车司机，不认识”。

深夜回家遭黑车司机尾随敲门 ，男子：我是送你回家的小哥哥。

当事女主回应深夜被司机尾随事件：因自己手机没电未付车费，司机想要回车费引起的误会，向司机道歉。

## 链接

- [嘉善女乘客不付车费反手小作文诬告案](https://weibo.com/1496883514/LxQ9AyeqQ)
- [嘉兴一女子凌晨打黑车被司机尾随至家门口，事后女子道歉称司机只是想要回车费。此事真实情况如何？](https://www.zhihu.com/question/537740161)
- [道歉视频-抖音](https://www.douyin.com/video/7109298829672959268)

**Comment by majinqiawa** [comment]
抄收了，由于目前issues过多，168小时内对新闻进行审核并登记
