### ISSUE TITLE
两女子酒后叫出租车，被拒载后当场暴揍司机

### ISSUE THREAD

**Issue by AOQNRMGYXLMV** [majinqiawa/xxn#37]
## 时间

2021年9月22日

## 地点

重庆渝北区

## 事件

朱先生通过手机接单到达渝北翠苹路指定位置，等待乘客。 

两名女乘客上车后要求朱先生开车，但朱先生在**已接其他客户单的情况下**拒绝了该两位女子。 

据朱先生介绍，两名女子都带着酒气，大声辱骂，他也骂了对方。两名女子下车后非常生气，其中一人采取了过激行为。女子把朱先生的手机摔了，朱先生立即下车与两名女子理论。 

一开始，白衣女子还在劝说，后来双方争吵起来，另一名深色衣服的女子对朱先生动了手。虽然一旁有路人上前劝阻，但两名女子情绪异常激动，朱先生说自己报了警，并准备上车将车挪到安全位置，深色衣服的女子直接坐到了驾驶室，对朱先生拳脚相加。事发后民警赶到现场，将双方带回派出所进行协调。 

## 链接

- [两女子酒后打车，与的哥发生冲突，双方一言不合动了手，车内监控画面独家披露……](https://www.douyin.com/video/7018145783744662814)
- [2女子酒后叫出租车，被拒载后当场暴揍司机，冲突升级孰是孰非？](https://www.ixigua.com/7085625142595977768?wid_try=1)
- [酒后打车发生抓扯 冲突升级孰是孰非？ ](https://www.sohu.com/a/494678249_121123778)

**Comment by majinqiawa** [comment]
抄收了，由于目前issues过多，168小时内对新闻进行审核并登记
