### ISSUE TITLE
女子高速乘车时持刀捅刺司机脖子，仅被拘役四个月

### ISSUE THREAD

**Issue by AOQNRMGYXLMV** [majinqiawa/xxn#38]
## 时间

2021年9月8日

## 地点

湖南临湘

## 事件

9月8日，湖南临湘，一女子在乘车时刺伤司机。监控显示，该女子坐在副驾驶，事前曾拿出刀反复观看、左顾右看、调整姿势后拿刀刺向司机脖子。司机当场流出鲜血，试图抵抗，随后女子又多次刺向司机。

经初步了解，刘某（女，30岁，湘潭人）当日从长沙乘坐受害人张某（男，55岁，浏阳人）驾驶的出租车（车牌号：湘A3**T）前往武汉，在途经京珠高速临湘段时用随身携带的水果刀将司机张某捅伤。

## 后续

2021年9月8日犯案，2022年1月7日判处拘役四个月，中间刚刚好四个月的时间一天不差，如果这段时间都在拘押状态，那直接抵完拘役期限，事实上的当庭释放。

![image](https://github.com/majinqiawa/xxn/assets/11152675/61f0324f-4f27-4349-b716-a6fbdb622c4d)

## 链接

- [高速上，女乘客突然拿刀猛刺司机颈部！连刺数刀…](https://www.sohu.com/a/490144451_121124477)
- [女子高速乘车时持刀捅刺司机脖子，交警：女子被带派出所、司机被送医。司机伤情如何？警方如何处理罪犯？](https://www.zhihu.com/question/485668562)
- [B站视频](https://www.bilibili.com/video/BV1e3411q7dY)

**Comment by majinqiawa** [comment]
抄收了，由于目前issues过多，168小时内对新闻进行审核并登记
