### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by magesep** [majinqiawa/xxn#4]
不要只有新闻链接 因为网页总会丢失 数据库也可能关闭 建议写个脚本呢 根据上传链接 爬取目前链接的网页快照存取进来

**Comment by Steven-Zhl** [comment]
不如保存离线网页留档一下

**Comment by majinqiawa** [comment]
我目前新闻是存了一个截图作为快照
摘一下我前面的评论 另外根据评论区大家的意见，新闻快照什么的我会搞的
我打算存两个新闻的截图，同时存一个B站客观报道的360p视频，后续一起传在文件夹

人脸识别的话我技术力目前做不到
