### ISSUE TITLE
杭州一女子虚构自己「跳车」，诬陷司机改变路线

### ISSUE THREAD

**Issue by AOQNRMGYXLMV** [majinqiawa/xxn#40]
## 时间

2021年8月25日

## 地点

浙江杭州

## 事件

杭州交通运输执法部门西湖大队接到一起有关出租车的投诉： 乘客翁女士说她遇到出租车绕道更改线路，她越想越怕，恐慌下就“跳车”了。

接到投诉后，执法队员高度重视，同时也产生疑惑：“遇到这种情况，乘客当时为何不报警？司机把乘客带到树林，有不轨想法？”

带着疑问，执法队员随即开展调查。在调取出租车车载视频资料时，发现这辆出租车车载系统终端老旧，属于杭州市最老的一批设备车辆，无法线上查询视频。

“通过查询车载视频和对司机李某某询问，我们发现事实跟翁女士的投诉有点出入。”执法队员小沈说。

事发当天，翁女士要前往澜花汇商务会所，由于司机方言口音重，两个人沟通目的地时，司机没有听清楚，在征得乘客同意下，司机把自己的手机递给翁女士，翁女士在地图APP上自己输入目的地——余杭互通。

“后来从司机李某某的手机导航记录里可以证实，导航地点确实是余杭互通，司机按照导航把车子开到了余杭互通。 车内录音显示，驾驶员与乘客并没有发生争执，翁女士是自己要求下车，没有‘跳车’。”执法队员小沈说。

翁女士觉得导航偏差，自己气不过，埋怨司机，就 虚构出“自己被拉到小树林，害怕跳车的戏码”。

随后，执法队员小沈对翁女士进行了批评教育：“不能因为心怀不满，而虚假投诉出租车驾驶员，驾驶员没有绕道，我们肯定不会处罚他，我们查明事实真相，就是要还他一个公道！”

## 链接

- [出租车更改路线致女乘客“跳车”？最终认定驾驶员无责](https://www.sohu.com/a/488389201_121123876)
- [出租车更改路线致女乘客“跳车”？背后有猫腻](https://zx.sina.cn/sh/2021-09-08/zx-iktzscyx3019946.d.html)

**Comment by AOQNRMGYXLMV** [comment]
## 时间
2022年1月24日

## 地点

海南陵水

## 事件

![image](https://github.com/majinqiawa/xxn/assets/11152675/cf6f5603-aa24-4c04-9661-6e0c6d54afcd)


一名女子为了让男友体验女性分娩的痛苦，把男友绑在体验器上，开着12级疼痛，硬生生折磨了男友三个小时，而巨大的疼痛也直接导致男子的小肠坏死被切除。

据悉，事发当时，女子和男友已经订婚，不过，女子的母亲和姐姐表示，为了能让男子体验女人生孩子时承受的痛苦，珍惜女人的不容易，便让男友去体验一次模拟分娩。

男友一开始也确实拒绝了这件事，谁知，女子却以结婚来要挟男友，并表示，如果你不去，婚就不结了。

男子也是十分无语，最后也勉强答应了，但事先也与女友一家说好，点到为止。

谁知，男子躺在了模拟分娩的床上，女友直接将男子固定住，随后便打开模拟分娩的机器，并把开关逐渐开大。

所谓的模拟分娩，是通过电流刺激肠道的方法让人感到疼痛，从而模拟分娩时的痛感，而等级越高，刺激的幅度也就越大。不过，合格的模拟分娩机器并不会对健康人造成身体上的损伤。

最开始男子还能忍受，不过当仪器开到8级的时候，男子已经不停地呻吟，并且冷汗直冒。谁知，女友见男子一脸痛苦，不仅不及时收手，还把强度加到了10级。

这下男子再也忍不了了，痛苦的呻吟变成了绝望的嘶吼，男子一边大吼着“问候”女友全家，一边让女友把绑在他身上的带子松开。

谁知，女友一边“贴心”的给男友擦汗，一边把强度加到了12级，这下男子已经没有了挣扎的力气，只能瘫倒在床上，喘着粗气。

就这样，男子被12级的强度刺激了足足90分钟，最终女友终于将仪器关掉。

回到家后，男子一直在呕吐，最终不得不去医院检查，被医生告知小肠坏死，需要切除。

对于男子的遭遇，男子的母亲十分气愤，不仅取消了婚约，还把女子一家告上法庭，谁知，女友却表示自己只是想让男子体验女人生孩子的痛苦，并没有恶意“故意折磨他”。

## 链接

- [女子让男友体验“模拟分娩”，折磨男友三小时，致男子小肠被切除 ](https://www.sohu.com/a/527843795_120952358)
- [女孩逼男友体验分娩，不顾求饶，亲手调到12级，男友直接住院了](https://www.toutiao.com/article/7094151461772591655)

**Comment by AOQNRMGYXLMV** [comment]
# 北邮研三学姐偷走4被喜茶

## 时间

2023年5月23日

## 地点

北京

## 事件

以下文字摘自受害者博客：

> 人文学院研三的该同学，作为已经25岁的成年人，在2023年5月22日晚间，因自称外卖被偷，在没有任何证据证明我与其有关的情况下，专门到北邮沙河校区外卖柜 A 柜84号柜，熟练地利用美团外卖柜的信用开柜功能，在明知该柜不可用她自己手机号打开的情况下，在确认柜内物品并非其本人所有的情况下，偷走了我和我同学购买的4杯喜茶。
> 在事情发生后，该同学在保卫处多次更改说法，多次撒谎，推卸责任、逃避问题。其声称是因为美团外卖柜出问题，导致本身B柜84号开成了A柜84号。实际上她故意且熟练地滥用了美团外卖柜的信用开柜功能，打开了不属于自己的外卖柜。她声称将偷走的喜茶放了回去。实际上她无法证明此事，甚至无法提供她放回的时间和地点以供调阅监控。
> 在处理问题时，该同学毫无歉意，一直在为自己的行为狡辩，还尝试用美团出现神奇故障等原因摆脱自己的责任，自始至终没有向我说过一句“对不起”“抱歉”的话。在我指出她没有给我道歉过时，她还狡辩说自己在转账时向我道过歉。但现场录音完整地覆盖了开始、转账、转账后至少10分钟，该同学从没有一句抱歉的话。

## 结果

研工部经过研究，已决定向涉事学姐给予警告处分。处分决定已经送达给学生。

## 链接

- [当事人博客——我在北邮被偷喜茶后的530个小时](https://blog.hzao.top/2023/05/27/bupt-heyteaevent/)

**Comment by majinqiawa** [comment]
抄收了，由于目前issues过多，168小时内对新闻进行审核并登记

**Comment by majinqiawa** [comment]
全部登记完成，您这种带链接和时间的对我非常友好，感谢您对仓库的贡献
