### ISSUE TITLE
女子搭公交非要前门下车，不顾司机阻拦，强按应急钮夺门而出

### ISSUE THREAD

**Issue by lc0a** [majinqiawa/xxn#45]
## 时间

2023年6月8日

## 地点

山东枣庄

## 事件

据时间直播消息，女子公交车上非要前门下车，司机拒绝后，让其从后面下车，女子称别耽误事，大家都有事。随后按下应急按钮强行下车。

公交公司回应北京时间记者：司机当时已报警，警方在处理。

## 链接

[B站（掌闻视讯）](https://www.bilibili.com/video/BV1Em4y1q7E8)

[抖音（时间直播）](https://www.douyin.com/video/7242509842806558009)

[女子公交上强行前门下车：按下“应急按钮”扬长而去](https://news.china.com/socialgd/10000169/20230609/45054845_all.html)

**Comment by majinqiawa** [comment]
抄收了，由于目前issues过多，168小时内对新闻进行审核并登记
