### ISSUE TITLE
2021年合肥杀害男童案

### ISSUE THREAD

**Issue by hydrodynamicfluid** [majinqiawa/xxn#47]
### [维基百科](https://zh.wikipedia.org/wiki/2021%E5%B9%B4%E5%90%88%E8%82%A5%E6%9D%80%E5%AE%B3%E7%94%B7%E7%AB%A5%E6%A1%88)

**Comment by majinqiawa** [comment]
抄收了，由于目前issues过多，168小时内对新闻进行审核并登记
