### ISSUE TITLE
4月30日，浙江金华，男子阻止插队遭两女子疯狂输出，男游客全程未与她们争吵。观观呼吁文明出游！

### ISSUE THREAD

**Issue by jerryyang-git** [majinqiawa/xxn#5]
## 来源
[【男子景区劝阻插队，遭两女子疯狂输出：你惹错人了!我就要插队】 ](https://www.bilibili.com/video/BV1Fk4y1E7RU/?share_source=copy_web&vd_source=de69f019d82c35282cb77f69c1ab5c30)

[四川“插队母女”火了，70岁外婆表情恶狠狠，被后面人盯上了](https://www.163.com/dy/article/I3VAB2S005561WO0.html)

**Comment by majinqiawa** [comment]
抄收了，稍后我看一下事件真实性，如果没问题的话24小时内登记，谢谢喵
