### ISSUE TITLE
2023-04 淄博烧烤诬告

### ISSUE THREAD

**Issue by helianchichi** [majinqiawa/xxn#50]
# 时间
2023-04
# 地点
山东淄博
# 事件
xxn诬告淄博老板宰客9元，老板娘出面证实为xxn自行拿取饮料小饼餐具逃单
# 链接
https://www.163.com/dy/article/I311O8KR05562XQM.html
https://www.163.com/dy/article/I3FN0J8H05562A36.html
https://www.sohu.com/a/670183145_121278857

**Comment by majinqiawa** [comment]
抄收了，48小时内审核并登记，您的格式很完美，非常便于收录，谢谢
