### ISSUE TITLE
2022-5 西安电子科技大学毕设代做事件

### ISSUE THREAD

**Issue by SanaeKochiya114514** [majinqiawa/xxn#51]
转帖：吐槽一下最近遇到的西电无赖（找代写论文还反让卖家赔钱）
(https://bbs.hupu.com/topic-daily)

原贴地址https://tieba.baidu.com/p/7845160506 （已删除）

反手威胁举报枪手，这真的感觉不像正常人类能做出来的事情。

![image](https://github.com/majinqiawa/xxn/assets/122459414/c4d423a5-e76f-4135-9328-89bd4031efd3)
![image](https://github.com/majinqiawa/xxn/assets/122459414/1995463c-98e5-49fc-a292-a48214ef4b9d)
![image](https://github.com/majinqiawa/xxn/assets/122459414/cc0bea41-6c65-4dd7-93b2-3fb6a4acc627)
![image](https://github.com/majinqiawa/xxn/assets/122459414/edd6163b-a0a8-4c56-81a6-1a56f19de80b)
![image](https://github.com/majinqiawa/xxn/assets/122459414/21d847bb-abee-46d0-a9c9-00d08e3ddce7)
![image](https://github.com/majinqiawa/xxn/assets/122459414/e0a72696-0573-426b-be6f-04ab53aeffc3)
![image](https://github.com/majinqiawa/xxn/assets/122459414/d0280a49-01e0-4958-91d1-41b11f9963e3)
![image](https://github.com/majinqiawa/xxn/assets/122459414/e2e67d02-1c5d-4d6a-90e4-9b17480e4a9b)
![image](https://github.com/majinqiawa/xxn/assets/122459414/6993a4b1-9b9d-401b-a065-ac6c38a3cebf)

**Comment by majinqiawa** [comment]
抄收了，此事件不容易核实，待查实或有报道后进行收录

**Comment by helianchichi** [comment]
该事件我记忆深刻，“卢雷元年”梗的出处，真实事件

# 补充链接
https://www.sohu.com/a/550423403_100215433

https://news.sciencenet.cn/htmlnews/2022/5/479587.shtm

https://new.qq.com/rain/a/20220531A0657000

**Comment by helianchichi** [comment]
> 抄收了，此事件不容易核实，待查实或有报道后进行收录

该事件我记忆深刻，“卢雷元年”梗的出处，真实事件，因为我也是2022年毕业答辩，受此影响毕业论文审查力度空前增大

# 补充链接
https://www.sohu.com/a/550423403_100215433

https://baike.baidu.com/item/%E5%8D%A2%E9%9B%B7%E5%85%83%E5%B9%B4/61211522

https://news.sciencenet.cn/htmlnews/2022/5/479587.shtm

https://new.qq.com/rain/a/20220531A0657000

**Comment by majinqiawa** [comment]
好的，核实后72小时内登记

**Comment by majinqiawa** [comment]
由于最近事情稍微多了点，争取明后天给您的新闻登记，不好意思

**Comment by majinqiawa** [comment]
已进行登记
