### ISSUE TITLE
男子制止校园霸凌被xxn怒怼围堵

### ISSUE THREAD

**Issue by zuoyejinxi** [majinqiawa/xxn#54]
![0070uxksgy1heulhbrd6nj30u0160jwi](https://github.com/majinqiawa/xxn/assets/138204183/2c573e89-4da5-454c-b450-ae9e351fdbf5)
男子教室仗义执言遭同... - @1024专员 的视频 - 视频 - 微博  https://weibo.com/tv/show/1034:4911249205690408?from=old_pc_videoshow

**Comment by majinqiawa** [comment]
抄收了，待核实后168小时内登记，谢谢
