### ISSUE TITLE
6月29日，重庆，女子想给自己的车充电，竟直接强拔旁边正在充电车辆的充电枪

### ISSUE THREAD

**Issue by guanosine-diphosphate** [majinqiawa/xxn#55]
B站网址：https://www.bilibili.com/video/BV1BP411i74h/

新浪网：女子强拔隔壁车辆充电枪被撞见
https://cj.sina.com.cn/articles/view/6418480627/m17e923df3033019rt2

腾讯网：女子强拔他人车辆充电枪想给自己车充电，被发现还不承认
https://new.qq.com/rain/a/20230630V058EO00

**Comment by guanosine-diphosphate** [comment]
不会搞pullreq也不会抓快照TAT

**Comment by guanosine-diphosphate** [comment]
再补充一个
网传一高校男生被女生喷不明液体，派出所：双方当事人已和解
https://new.qq.com/rain/a/20230701A06VWN00
https://www.163.com/news/article/I8JBBTJN0001899O.html
但是目前好像还没有官方通报

**Comment by majinqiawa** [comment]
抄收了，第一个待核实后168小时内收录，第二个待确定后审核收录
