### ISSUE TITLE
军训女生油漆开水泼人

### ISSUE THREAD

**Issue by Lithiio** [majinqiawa/xxn#56]
相关视频链接：
BV1Mh411A7nv
BV1GX4y1W7Lq
BV1gs4y1k782
BV11X4y1q7hn
![IMG_5284](https://github.com/majinqiawa/xxn/assets/138313098/ab9f94fe-16a9-4dcc-b41f-8e5988ad811d)

**Comment by Lithiio** [comment]
补充资料：
https://www.zjxz.edu.cn/2023/0702/c21a17810/page.htm

**Comment by majinqiawa** [comment]
这件事有很多人发过了，但是由于发生了没几天，先让子弹飞一会，看看后续处理情况等后一并收录，谢谢
