### ISSUE TITLE
2019年01月12日 长春大一女生坐网约车犯困 怀疑被下药拿刀划伤司机 事后警方自费赠与女生1500元

### ISSUE THREAD

**Issue by FDrag0n** [majinqiawa/xxn#6]
新闻出处
[长春大一女生坐网约车犯困 怀疑被下药拿刀划伤司机](https://news.sina.com.cn/s/2019-01-15/doc-ihqfskcn7365225.shtml)

这都部署于魔法伤害减免了，这属于物理吸血效果了

**Comment by FDrag0n** [comment]
![image](https://github.com/majinqiawa/xxn/assets/34733637/e547e815-2fa4-4be1-8df7-66c2cc4b80c9)
评论区才是真亮点

**Comment by FDrag0n** [comment]
新文化报官微已经删除该文章，仅微博和部分转载媒体仍然保留

**Comment by acsxzz** [comment]
评论是真的群英荟萃
