### ISSUE TITLE
你的目的是什么

### ISSUE THREAD

**Issue by clverhack** [majinqiawa/xxn#60]

**Comment by Ryuchen** [comment]
collection

**Comment by VanTesla** [comment]
本仓库的目的在于让每一位同志能够平等的认识到男女之间目前的地位差别，无论您是男性还是女性，我们从根本不存在任何的相互歧视，包括为仓库提issues的贡献者，他们中也有女性，也有男性，来自不同的阶层，不同的职业，但是我们的理想是一致的，我们的这个仓库，目的是为了让男女之间可以获得平等的权力，而不是相互歧视，相互打压，这并不是我们任何人想看到的，仓库一开始的初衷也不是像一些女性所说的恶意整合亦或者怎么样，我们也能看见，仓库的100%新闻都是来自于权威新闻机构，并且也是我经过了多方面证实才会收录，这一切的一切，都是一个事实，我们每个人都不应该忽视这些事实，更不应该扭曲这些事实，这也就是这个仓库存在的意义，这个仓库从创建开始，就不是为了挑起性别对立亦或者是歧视女性的恶意整合，从一开始，初衷便是让男女之间，能获得平等的权力。

**Comment by majinqiawa** [comment]
我的目的在仓库的readme.md
你作为一个会上github的人，熟读readme再提issues是必须的
