### ISSUE TITLE
浙江师范大学行知学院一女大学生厌男泼男生开水,仅仅留校查看

### ISSUE THREAD

**Issue by yanguangshaonian** [majinqiawa/xxn#62]
[图1](https://nimg.ws.126.net/?url=http%3A%2F%2Fdingyue.ws.126.net%2F2023%2F0704%2F01f92232j00rx9ibu0033d000hs00rsp.jpg&thumbnail=660x2147483647&quality=80&type=jpg)

**Comment by yanguangshaonian** [comment]
https://www.163.com/dy/article/I8QJ5C1K055631K1.html

**Comment by yanguangshaonian** [comment]
浙江师范大学行知学院一女大学生贾某某在军训期问，屏蔽班级所有”男同学，发
表针对男同学的不当言论。
接连发出多条动态，字里行间的思想都非常极端，对男生表示很不满

**Comment by majinqiawa** [comment]
这件事有很多人发过了，但是由于发生了没几天，先让子弹飞一会，看看后续处理情况等后一并收录，谢谢
