### ISSUE TITLE
建议增加可信度条目

### ISSUE THREAD

**Issue by bbbccvbvv** [majinqiawa/xxn#63]
当前很多新闻首先的爆发点都是网络或自媒体，但是消息的来源对于普通网友来说很难验证，总有人一厢情愿的全部相信或全部否决，建议新闻加上可信度，简单点就加存疑和实锤，不传播假消息。

**Comment by majinqiawa** [comment]
我这里的新闻基本上都是99.99可信度的，不存在一些不可信的新闻，如果后续发现有变化的新闻我也会第一时间进行修改/删除的
