### ISSUE TITLE
2023.07.06 女生自己作弊反而倒打一耙

### ISSUE THREAD

**Issue by afresh** [majinqiawa/xxn#67]
8.74 eOK:/ 复制打开抖音，看看[游戏收藏家的作品]女生自己作弊反而倒打一耙# 小仙女 # 趣事 # ... https://v.douyin.com/irLeuWH/

大致就是xxn考试前9名考生都是男生怀疑男生集体作弊
得到老师否认后认为老师也是男的跟男学生一起勾结包庇拉高分数
老师表示你不服就找学校，结果xxn真找到学校调监控，最后男生不仅没作弊，反而自己偷偷用手机作弊被发现了
最后xxn表示我用手机搜的答案才考了第10，男老师跟男学生不是包庇是什么

![fb9b13eb5ca17b1d617b855228441c5](https://github.com/majinqiawa/xxn/assets/5461256/07b8be3a-2137-44cf-a7bc-83be99eafdf5)

**Comment by majinqiawa** [comment]
抄收了，审核后168小时内登记，谢谢
