### ISSUE TITLE
不明白为啥老是有人喜欢搞这种

### ISSUE THREAD

**Issue by longgui0318** [majinqiawa/xxn#68]
有人出钱在github上反就算了，还有一些打着莫名其妙的幌子，放一些莫名其妙的内容。
作为技术，看到github上充斥这种，却无法举报关闭，我很无奈。

没有秉承就事论事原则，挂个平等自由名义，着实可笑

**Comment by metalgee** [comment]
https://docs.github.com/zh/communities/maintaining-your-safety-on-github/reporting-abuse-or-spam

**Comment by longgui0318** [comment]
你知道举报了没用，你也知道为什么没用。但这不代表对。虽然无所谓对错。

本不会理会这种，但这样的内容居然能上排行榜，真的觉得有点丢人。

**Comment by exumeOAO** [comment]
好家伙，在GitHub存储点旧闻，注意是旧闻，你都能扣上反贼的这顶大帽子，什么pxj，笑死。
还有你知不知道存储信息无法做到100%无损，要想能够安全存储，就必须要勤于更换信息存储源？
存储点旧闻，还就事论事，连论这个动作都没有，就开始批判了？
原来国内言论自由就被你这样的一点ac数都没有的人给弄没了，你自己要好好反思，而不是指责别人去反思。

**Comment by longgui0318** [comment]
呵呵，没有秉承就事论事原则，挂个平等自由名义，着实可笑。

你有没有去数，我不知道，装个X还是你厉害

**Comment by longgui0318** [comment]
哪句提到反，谁扣帽子，你这句话，你自己心里去数数看，再说呗，睁着眼说瞎话，谁能阻止你。

**Comment by exumeOAO** [comment]
《有人出钱在github上反就算了，还有一些打着莫名其妙的幌子，放一些莫名其妙的内容》
《哪句提到反，谁扣帽子，你这句话，你自己心里去数数看，再说呗，睁着眼说瞎话，谁能阻止你》
典中典中典，笑死。
养电子宠物真有意思，拿根狗尾巴草逗一逗，就会汪汪汪的狗叫，让虚无的一天变得充实了起来。

**Comment by longgui0318** [comment]
厉害，这句话是【扣上反贼的这顶大帽子】？你这自然语言理解能力，建议让人工智能替你活吧。真的，衷心祝福，以后的路走的顺。

**Comment by KeranBeHappy** [comment]
陈述客观事实叫反？老子民族主义者又红又专比你红得专的多的多的多，但是这并不妨碍我看xxn不爽，你在这里狗叫什么。

**Comment by longgui0318** [comment]
让你们叫。好好叫，真的，理解能力多提升一下。
