### ISSUE TITLE
这作者是不是脑子有病？

### ISSUE THREAD

**Issue by windgentle** [majinqiawa/xxn#69]
这也能上排行榜，脏了我的眼！

**Comment by WhitePhosphor** [comment]
?

**Comment by lightingLion** [comment]
急死了

**Comment by Lithiio** [comment]
你觉得有病可以去自己的圈子里挂捏，没必要在这里骂，脏了你的眼
脏了你的眼，你还特地骂几句，实在是坚守原则👍

**Comment by WhitePhosphor** [comment]
都开炮了那我也来掺和一脚奥
你要是真觉得脏了你的眼还在这里面骂怎么不把你眼珠子扣下来烧给美羊羊给你的眼睛净化一下呢😋
你要是真觉得脏了你的眼还在这里骂你怎么还要当个joker看着这个repo无能狂怒大发雷霆却只能无可奈何悻悻然骂一句脏了你的眼睛呢😋
你要是真觉得脏了你的眼还在这里骂你怎么还要当个沸羊羊跪舔你的女神大人做这点让人啼笑是非的事情博得一点低到可怜的存在感呢😋
好好看看这里是什么场合可以吗 gayhub 连润学这种东西都能挂在上面我们的东西怎么就不能挂在上面了？一到这种时候开始装聋作哑一句话也说不出来了是吗😋

**Comment by VVIZE-ops** [comment]
这么气急败坏，是戳到你痛点了？

**Comment by zrjcoder** [comment]
🐢🐢🐢🐢🐢🐢🐢

**Comment by whleecn** [comment]
做事的人没病，写成新闻稿的人没病，传播的人没病，模仿的人没病，偏偏收集整理的人有病，是这样吗？

**Comment by Dqqaz** [comment]
> 这也能上排行榜，脏了我的眼！
🐢男小仙女滚一边去，别侮辱了github，是是🐢男就去阉了，别有你这种fw杂碎生下来的低质后代，降低中国幼孩质量
阉割参考视频:https://www.bilibili.com/video/BV1F84y1p7wK

**Comment by VVIZE-ops** [comment]
> > 这也能上排行榜，脏了我的眼！
> > 🐢男小仙女滚一边去，别侮辱了github，是🐢男就去阉了，别有你这种fw杂碎生下来的低质后代，降低中国幼孩质量
> > 阉割参考视频:https://www.bilibili.com/video/BV1F84y1p7wK

小仙女这么厉害，自己去无性繁殖啊，我建议学习女儿国，直接去建国，然后在发明子母河，而且生了之后直接紫砂，毕竟自己也是两性繁衍出来的低质后代，坏了你们女儿国的血统

**Comment by kireirain** [comment]
他只是把真相push出来罢了

**Comment by Aurora-Simba** [comment]
是不是都在骂你，戳到你痛点了呀

**Comment by Hanxven** [comment]
这 repo 能记录这么多东西，估计也有你的一份功劳

**Comment by budhubhud** [comment]
你找你妈画面啊废物 成为众xxn中少数能上来的你觉得自己很优越了？

**Comment by WhitePhosphor** [comment]
> 你找你妈画面啊废物 成为众xxn中少数能上来的你觉得自己很优越了？

支持正义爆杀

**Comment by chenjh3061** [comment]
这不都是现实的事实吗？很符合我对仙女的印象，讲事实==下贱，抛开事实不谈才是好家伙捏~

**Comment by majinqiawa** [comment]
好了好了，挂的够久了，把你close了

**Comment by exumeOAO** [comment]
> 

你在自我介绍吗？笑死

**Comment by KeranBeHappy** [comment]
鳖在这理发店。

> 这也能上排行榜，脏了我的眼！

**Comment by A13437858** [comment]
被砸到了就开始叫了
