### ISSUE TITLE
开放评论区（Discussion）

### ISSUE THREAD

**Issue by ttimasdf** [majinqiawa/xxn#71]
可以针对每条新闻在 Discussion 里创建一个对应的 thread，供大家讨论或投票。

当然用脚想都知道，最后评论区肯定大部分都是 hate speech，如果 discussion 有自动化的 moderation 的话也许才可以这么考虑，但似乎 discussion 那块是没有 API 的吧，我记得好像是。

**Comment by majinqiawa** [comment]
我的想法是，如果开放讨论和投票，可能会被官方或者什么，以讨论违规等等方式要端掉
毕竟目前我们还是要小心一些，可能等后续再考虑吧
谢谢
