### ISSUE TITLE
男子教室仗义执言遭同学怒怼

### ISSUE THREAD

**Issue by Lithiio** [majinqiawa/xxn#72]
6月11日，北京。一则“男子教室仗义执言遭同学怒怼”的视频在网络传播，有网友称视频中的学生为北京政法职业学院学生。对此，北京政法职业学院回应称：学校非常重视该事件，第一时间核查事实，目前核查情况为学生在课间发生了言语冲突，当时老师和辅导员对双方进行了调解。视频只录了后半段，没有前半段，该事件公安机关已介入，正在调查取证，学校在准备通报中。（环球网）

BV1kM4y1L74i（中国新闻周刊）
BV118411Z7Tb（环球网）

补充：BV1ug4y1P7GK（红星视频）
学校工作人员称视频“掐头去尾”，可以先占个坑等到有后续了再说。虽然可能没有后续了

根据中国新闻周刊消息，目前男生已自曝退学。

**Comment by majinqiawa** [comment]
抄收了，审核后168小时内登记，谢谢
