### ISSUE TITLE
2021年货拉拉乘客跳车事件

### ISSUE THREAD

**Issue by mjei8676** [majinqiawa/xxn#73]
https://zh.wikipedia.org/zh-hans/2021%E5%B9%B4%E8%B4%A7%E6%8B%89%E6%8B%89%E4%B9%98%E5%AE%A2%E8%B7%B3%E8%BD%A6%E4%BA%8B%E4%BB%B6

**Comment by majinqiawa** [comment]
该事件由于社会舆论过大，且知名度高，个人为了防止仓库被爆破，暂时不予收录，谢谢

**Comment by mjei8676** [comment]
那不如都别收录了
