### ISSUE TITLE
无锡蛋糕店老板被诬陷案

### ISSUE THREAD

**Issue by LMDM387** [majinqiawa/xxn#79]
警方通报地址:https://picx.zhimg.com/100/v2-9227648bfafdea744f5c7b6fff8d5c9f_r.jpeg

后续结果:蛋糕店老板起诉诬陷，女性以跳楼相逼，最终老板撤诉

相关知乎提问:https://www.zhihu.com/question/611486302

**Comment by majinqiawa** [comment]
抄收了，审核后168小时内登记，谢谢

**Comment by summer-breeze123** [comment]
真的是，越来越恶劣
