### ISSUE TITLE
建议以年份月份作为分类目录

### ISSUE THREAD

**Issue by RockChinQ** [majinqiawa/xxn#8]
并在README.md链接每个事件，以便在事件过多时很好地整理

**Comment by ZM-J** [comment]
可以做一个前端 按照省份来归类 对各省的xxn上分行为进行动态统计 统计各赛季各省xxn段位捏😀

**Comment by majinqiawa** [comment]
我对于md语法不是很熟悉，在readme整理目录这方面有大佬愿意帮忙的话可以发个邮件吗？
majinqi@yutangcity.top

**Comment by majinqiawa** [comment]
感谢这位大佬aaaa
