### ISSUE TITLE
小仙女因为拼车的是外卖小哥而拒绝上车

### ISSUE THREAD

**Issue by Dqqaz** [majinqiawa/xxn#80]
发生时间:200727
视频:https://v95-sh.douyinvod.com/79d2e96cbee6ca64493b0519e1c44d8c/64ae48b2/video/tos/cn/tos-cn-ve-15c001-alinc2/owyQfAfErgpZkL7DsEBM9rAACiIIFHAwD3C8xn/?a=1128&ch=10010&cr=13&dr=0&lr=all&cd=0%7C0%7C0%7C&cv=1&br=370&bt=370&cs=2&ds=6&ft=z4Nmo0llUpGitLusvusEvMHq4gd3XNnAyE1Uc6B3OJEDXPjDHDDqIYG0vT3gkfuo&mime_type=video_mp4&qs=11&rc=Z2k8Nzk3Omg8PGZkPDs3N0BpanlpN3U5cjV2bDMzNGkzM0AvXl9iXjYuXy0xYS9hNV4yYSNxXzVvMmRzM2dgLS1kLTBzcw%3D%3D&l=202307121330130DC3E67A1927D86DE515&btag=e010a8008&cc=4b&cdn_type=1&pdp=xyp0&pwid=24

https://v27-cold.douyinvod.com/28c284b41c818b1c5890da6d0e100fad/64ae48e2/video/tos/cn/tos-cn-ve-15c001-alinc2/osR9vCkAtDf6VhcbnAgEAh8YdRABQgbbDeA8gq/?a=1128&ch=11&cr=13&dr=0&lr=all&cd=0%7C0%7C0%7C&cv=1&br=447&bt=447&cs=2&ds=6&ft=KQ9BF3UUmf.ud~D1BD1YBa_3pt2Gs6rkUYWmx4kgG54kEvjThK&mime_type=video_mp4&qs=11&rc=ZWRoaDM2ZGRoOjQ2ZGU3ZEBpajNqZDk6ZnJnbDMzNGkzM0A1LWMuLl8yXjYxXzVgYDIuYSMwLy1zcjRfazBgLS1kLS9zcw%3D%3D&l=20230712133040E5B1A9BE1FBCC17FB3AB&btag=e010a8008&cdn_type=1&pwid=24

**Comment by majinqiawa** [comment]
抄收了，审核后168小时内登记，谢谢
