### ISSUE TITLE
烦请添加女教师课堂上质疑南京大屠杀遇难人数

### ISSUE THREAD

**Issue by exumeOAO** [majinqiawa/xxn#87]
烦请添加一下女教师课堂上质疑南京大屠杀遇难人数，十分感谢！时间和参考链接如下。
时间：2021年12月
参考链接：https://www.chinapeace.gov.cn/chinapeace/c100007/2021-12/16/content_12571633.shtml

**Comment by majinqiawa** [comment]
抄收了，240小时内添加
