### ISSUE TITLE
烦请添加TFBOYS粉丝、陪睡、抢位置持械打架

### ISSUE THREAD

**Issue by exumeOAO** [majinqiawa/xxn#88]
烦请添加一下TFBOYS粉丝、陪睡、抢位置持械打架的相关内容，十分感谢！时间和相关链接如下。
时间：2023年8月
相关链接：
https://m.thepaper.cn/newsDetail_forward_24136039
https://zhuanlan.zhihu.com/p/648170341

**Comment by majinqiawa** [comment]
抄收了，240小时内添加
