### ISSUE TITLE
千万粉丝网红诬告老板性骚扰，同伙不服判决辩称“背后有资本”

### ISSUE THREAD

**Issue by jerryyang-git** [majinqiawa/xxn#9]
## 来源

[【千万粉丝网红诬告老板性骚扰，同伙不服判决辩称“背后有资本”】 ](https://www.bilibili.com/video/BV1Mg4y1c7zi/?share_source=copy_web&vd_source=de69f019d82c35282cb77f69c1ab5c30)

**Comment by majinqiawa** [comment]
抄收了，稍后我看一下事件真实性，如果没问题的话24小时内登记，谢谢喵
