### ISSUE TITLE
男子店内吃早餐被陌生女子强吻

### ISSUE THREAD

**Issue by ztw321** [majinqiawa/xxn#91]
【男子吃早餐时突然被陌生女子强吻，亲完女子淡定离去留下男子原地懵圈】 https://www.bilibili.com/video/BV18P41147rN/
https://weibo.com/1323527941/Ncx3CE0db
https://baijiahao.baidu.com/s?id=1773097919454678089&wfr=spider&for=pc

导语：7月31日，福建。小伙上班前在早餐店吃早餐，一陌生女子突然进来强吻后淡定离开，小伙当时以为搭在肩膀上的手是同事，反应过来的时候已经懵了，店内其他人也惊呆了，男子称事后已报警处理，网友：男孩子出门在外一定要保护好自己！

**Comment by majinqiawa** [comment]
抄收了，168小时内添加
