### ISSUE TITLE
烦请添加订婚后第四天女方控告男方强奸，男方被刑拘

### ISSUE THREAD

**Issue by exumeOAO** [majinqiawa/xxn#92]
烦请添加一下订婚后第四天女方控告男方强奸，男方被刑拘，十分感谢！时间和参考链接如下。
时间：2023年8月
参考链接：
https://news.china.com/socialgd/10000169/20230821/45332515_4.html
https://www.zhihu.com/question/618276160

**Comment by xianbeisukisu** [comment]
臣附议

**Comment by exumeOAO** [comment]
哈喽，是事实不对吗？这条怎么下架了？
