### ISSUE TITLE
萝莉街头乱停车被阻单挑十余人

### ISSUE THREAD

**Issue by ztw321** [majinqiawa/xxn#96]
https://weibo.com/1647210043/NgXJXaGFI?refer_flag=1001030103_

【女孩将共享单车停放在步行街口遭保安劝阻 随后打骂保安及劝架的路人】 https://www.bilibili.com/video/BV1r8411z76H/

https://news.china.com/socialgd/10000169/20230830/45374166_all.html#page_2

https://news.china.com/socialgd/10000169/20230831/45375610_all.html

【[#萝莉街头乱停车被阻单挑十余人#]被保安阻拦瞬间暴怒】8月29日，福建福州平潭县步行街两名女子与保安发生纠纷，一名身着萝莉裙的女生用脚踢踹保安。从此处路过的一名戴帽子老人上前劝阻，遭女生用手部击打，与老人同行的女子立即上前还击。视频中，女生被对方拍打、拽倒，老人还向其腹部踢踹。据步行街物业工作人员称，女生违规停放共享电动车遭阻拦便动手打保安，争执期间，女生还与多名路人发生打斗，自己也被踢踹、推倒。事发后，城关派出所民警到现场处置，将女生和涉事人员带走，因女生未满18岁，民警对其进行了训诫。

**Comment by majinqiawa** [comment]
抄收了，168小时内审核并根据审核结果处理(添加或未过审)
感谢您对仓库的贡献与支持！
